"""SilenceRequest — typed schema for remediation actions.

Represents a single silence/mute request constructed by the analytics
engine.  The schema is provider-agnostic — concrete providers map it
to their own API payload shape.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class SilenceRequest:
    """A request to silence a cluster of duplicate/cascade alerts.

    Parameters
    ----------
    alert_ids
        Identifiers of the alerts to silence.
    reason
        Human-readable explanation (generated by the analytics engine).
    source
        What triggered this silence: ``"dedup"``, ``"cascade"``,
        or ``"manual"``.
    dry_run
        When ``True`` the payload is built and returned but **never**
        sent to the provider API.
    cluster_metadata
        Optional context from the analytics engine — e.g. similarity
        score, cascade root-cause index, time window.
    """

    alert_ids: list[str]
    reason: str
    source: str = "manual"
    dry_run: bool = False
    cluster_metadata: dict[str, Any] = field(default_factory=dict)

    def to_provider_payload(self, provider: str = "generic") -> dict[str, Any]:
        """Build the API payload shape for the given provider.

        Parameters
        ----------
        provider
            Target provider name.  Different providers expect different
            payload shapes; this method adjusts the output accordingly.

        Returns
        -------
        dict
            Provider-specific payload dict.
        """
        base = {
            "reason": self.reason,
            "source": self.source,
            "dry_run": self.dry_run,
        }
        if provider == "opsgenie":
            # Opsgenie /v2/mute-rules expects:
            #   { "filter": { "condition": … }, "reason": …, "enabled": true }
            return {
                **base,
                "filter": {
                    "condition": " OR ".join(f'id = "{aid}"' for aid in self.alert_ids),
                },
                "enabled": not self.dry_run,
            }
        if provider == "datadog":
            # Datadog expects: { "scope": …, "message": …, "active": bool }
            return {
                **base,
                "scope": " OR ".join(f"alert_id:{aid}" for aid in self.alert_ids),
                "message": self.reason,
                "active": not self.dry_run,
            }
        # Generic / mock provider — flat payload
        return {
            **base,
            "silenced_ids": self.alert_ids,
        }

    def dry_run_summary(self) -> str:
        """Human-readable summary of what *would* happen."""
        lines = [
            "🔇 Dry-Run Silence Request",
            f"   Source:     {self.source}",
            f"   Reason:     {self.reason}",
            f"   Alert IDs:  [{', '.join(self.alert_ids)}]",
            "   Payload:    (see below)",
        ]
        return "\n".join(lines)
